package com.wadpam.tracker.dao;

import com.wadpam.tracker.domain.DParticipant;

/**
 * Business Methods interface for entity DParticipant.
 * This interface is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2014-02-02T15:08:33.821+0100.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public interface DParticipantDao extends GeneratedDParticipantDao {

    final Integer STATUS_PENDING = 1;
    final Integer STATUS_FINISHED = 9;
	
    Iterable<DParticipant> queryPending(long raceId);
}
