package com.wadpam.tracker.dao;

import com.wadpam.tracker.domain.DParticipant;
import net.sf.mardao.core.Filter;

/**
 * Implementation of Business Methods related to entity DParticipant.
 * This (empty) class is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2014-02-02T15:08:33.821+0100.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public class DParticipantDaoBean 
	extends GeneratedDParticipantDaoImpl
		implements DParticipantDao 
{
    @Override
    public Iterable<DParticipant> queryPending(long raceId) {
        Filter raceFilter = createEqualsFilter(COLUMN_NAME_RACEID, raceId);
        Filter statusFilter = createEqualsFilter(COLUMN_NAME_STATUS, STATUS_PENDING);
        return queryIterable(false, 0, -1, null, null, null, false, null, false, raceFilter, statusFilter);
    }

}
