package com.wadpam.tracker.dao;

import com.wadpam.tracker.domain.DSplit;
import java.util.TreeMap;

/**
 * Implementation of Business Methods related to entity DSplit.
 * This (empty) class is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2014-02-11T19:20:04.353+0100.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public class DSplitDaoBean 
	extends GeneratedDSplitDaoImpl
		implements DSplitDao 
{

    @Override
    public TreeMap<Long, DSplit> mapByParentKey(Object raceOrParticipantKey) {
        final TreeMap<Long, DSplit> raceSplits = new TreeMap<Long, DSplit>();
        for (DSplit s : queryByRaceKey(raceOrParticipantKey)) {
            raceSplits.put(s.getTimestamp(), s);
        }
    
        return raceSplits;
    }


}
